# Generated by Django 4.2 on 2023-04-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_objectives', models.IntegerField()),
                ('delivering_material', models.IntegerField()),
                ('engaging_students', models.IntegerField()),
                ('responding_questions', models.IntegerField()),
                ('providing_feedback', models.IntegerField()),
                ('inclusive_environment', models.IntegerField()),
                ('using_technology', models.IntegerField()),
                ('promoting_critical_thinking', models.IntegerField()),
                ('challenging_students', models.IntegerField()),
                ('overall_satisfaction', models.IntegerField()),
            ],
        ),
    ]
