# Generated by Django 4.2 on 2023-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_member', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('delivery', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('responsiveness', models.IntegerField()),
                ('feedback', models.IntegerField()),
                ('inclusiveness', models.IntegerField()),
                ('technology', models.IntegerField()),
                ('critical_thinking', models.IntegerField()),
                ('motivation', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
