# Generated by Django 4.2 on 2023-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_courseevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyRating',
        ),
        migrations.AddField(
            model_name='courseevaluation',
            name='evaluator',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseevaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
