# Generated by Django 4.2 on 2023-04-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_surveyrating_courseevaluation_evaluator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseevaluation',
            name='total_average',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseevaluation',
            name='evaluator',
            field=models.TextField(blank=True),
        ),
    ]
